
import React, { useState, useEffect, useRef } from 'react';
import { createRoot } from 'react-dom/client';
import { GoogleGenAI } from "@google/genai";
import ReactMarkdown from 'react-markdown';
import { Sparkles, BookOpen, RotateCcw, History, Share2, ArrowLeft, Zap, Cpu, AlertTriangle, Terminal, Eye, ShieldCheck, Wifi, Lock, Globe } from 'lucide-react';

// --- Types ---
type View = 'HOME' | 'TAROT' | 'ANSWER_BOOK';
type Lang = 'ZH' | 'EN';

interface TarotCard {
  name: string;
  nameCN: string;
  imageUrl: string;
  upright: string; // Keywords for AI context (can be Chinese, AI handles translation)
  reversed: string;
}

interface DrawnCard extends TarotCard {
  isReversed: boolean;
  position: string; // Position name
  positionKey: string; // Internal key for translation
}

interface HistoryItem {
  id: string;
  type: 'TAROT' | 'ANSWER';
  date: string;
  query: string;
  result: string; 
  details?: DrawnCard[]; 
}

// --- Translations ---
const TRANSLATIONS = {
  ZH: {
    systemStatus: '系统在线',
    abort: '中断协议',
    footer: 'NEO-ORACLE V3.0.1 // 已连接',
    disclaimer: '免责声明: 本终端生成的所有数据仅供娱乐参考。命运由用户自身的代码（Code）决定。',
    heroTitle: '赛博玄学终端',
    heroSubtitle1: '连接数字虚空',
    heroSubtitle2: '解析二进制命运',
    heroReady: '系统已就绪，请选择连接协议...',
    tarotTitle: '赛博塔罗',
    tarotDesc: '调用 Rider-Waite 数据库，全息解析过去、现在与未来的数据流。',
    answerTitle: '答案之书',
    answerDesc: '向矩阵核心提问，获取来自混沌算法的神谕指引。',
    historyBtn: '数据日志',
    
    // Tarot View
    tarotSetupTitle: '建立连接协议',
    tarotTarget: '查询目标 (TARGET)',
    tarotPlaceholder: '输入你的困惑 (留空则默认扫描整体运势)...',
    tarotAlgo: '选择算法 (ALGORITHM)',
    tarotSingle: '单牌指引',
    tarotSingleDesc: 'Single Bit Processing',
    tarotTime: '圣三角时间流',
    tarotTimeDesc: 'Past - Present - Future',
    tarotBtn: '初始化抽牌程序',
    tarotShuffling: '随机化比特...',
    tarotAccessing: '正在访问量子熵池...',
    tarotReportTitle: '系统分析报告',
    tarotStatusProcessing: '处理中',
    tarotStatusComplete: '完成',
    tarotDecrypting: '正在解密大阿卡纳元数据...',
    tarotAnalyzing: '正在分析卡牌位置与逆位数据...',
    tarotConnecting: '正在连接意识云端...',
    tarotGenerating: '正在生成叙事...',
    tarotReset: '重置系统 (RESET)',
    
    // Answer Book
    abTitle: '答案之书',
    abInputPlaceholder: '在此输入查询...',
    abBtnIdle: '查询矩阵 (EXECUTE)',
    abBtnBusy: '计算中...',
    abNewQuery: '新查询',
    abSubject: '主题',
    
    // History
    histTitle: '数据日志 (Logs)',
    histPurge: '清除数据',
    histRecent: '近期记录',
    
    // Common
    errNoKey: '系统错误：缺少API密钥。请联系管理员。',
    errConnect: '错误：与神谕网络的连接被防火墙拦截。请稍后再试。',
    errSignalLost: '信号丢失',
  },
  EN: {
    systemStatus: 'SYSTEM ONLINE',
    abort: 'ABORT PROTOCOL',
    footer: 'NEO-ORACLE V3.0.1 // CONNECTED',
    disclaimer: 'DISCLAIMER: All data generated by this terminal is for entertainment only. Fate is determined by your own Code.',
    heroTitle: 'CYBER ORACLE',
    heroSubtitle1: 'Connect to Digital Void',
    heroSubtitle2: 'Parse Binary Fate',
    heroReady: 'System ready. Select connection protocol...',
    tarotTitle: 'CYBER TAROT',
    tarotDesc: 'Access Rider-Waite database. Holographic analysis of Past, Present, and Future data streams.',
    answerTitle: 'ANSWER BOOK',
    answerDesc: 'Query the Matrix Core. Retrieve oracle guidance from chaos algorithms.',
    historyBtn: 'DATA LOGS',
    
    // Tarot View
    tarotSetupTitle: 'ESTABLISH CONNECTION',
    tarotTarget: 'TARGET QUERY',
    tarotPlaceholder: 'Input your query (Leave empty for general system scan)...',
    tarotAlgo: 'SELECT ALGORITHM',
    tarotSingle: 'Single Bit Guide',
    tarotSingleDesc: 'Single Bit Processing',
    tarotTime: 'Trinity Time Flow',
    tarotTimeDesc: 'Past - Present - Future',
    tarotBtn: 'INITIALIZE DRAW',
    tarotShuffling: 'RANDOMIZING BITS...',
    tarotAccessing: 'Accessing quantum entropy pool...',
    tarotReportTitle: 'SYSTEM ANALYSIS REPORT',
    tarotStatusProcessing: 'PROCESSING',
    tarotStatusComplete: 'COMPLETE',
    tarotDecrypting: 'Decrypting Major Arcana metadata...',
    tarotAnalyzing: 'Analyzing card positions and inversions...',
    tarotConnecting: 'Connecting to consciousness cloud...',
    tarotGenerating: 'Generating narrative...',
    tarotReset: 'SYSTEM RESET',
    
    // Answer Book
    abTitle: 'THE BOOK',
    abInputPlaceholder: 'INPUT QUERY HERE...',
    abBtnIdle: 'QUERY MATRIX (EXECUTE)',
    abBtnBusy: 'COMPUTING...',
    abNewQuery: 'NEW QUERY',
    abSubject: 'SUBJECT',
    
    // History
    histTitle: 'DATA LOGS',
    histPurge: 'PURGE DATA',
    histRecent: 'RECENT LOGS',
    
    // Common
    errNoKey: 'SYSTEM ERROR: Missing API Key. Contact Admin.',
    errConnect: 'ERROR: Connection to Oracle Network blocked by firewall. Try again later.',
    errSignalLost: 'SIGNAL LOST',
  }
};

// --- Tarot Deck Data (Rider-Waite Major Arcana) ---
const MAJOR_ARCANA: TarotCard[] = [
  { name: 'The Fool', nameCN: '愚者', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/90/RWS_Tarot_00_Fool.jpg', upright: '新的开始，冒险，潜力', reversed: '鲁莽，轻率，被利用' },
  { name: 'The Magician', nameCN: '魔术师', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/de/RWS_Tarot_01_Magician.jpg', upright: '创造力，能力，意志', reversed: '欺骗，能力不足，混乱' },
  { name: 'The High Priestess', nameCN: '女祭司', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/88/RWS_Tarot_02_High_Priestess.jpg', upright: '直觉，神秘，潜意识', reversed: '表面，无知，压抑' },
  { name: 'The Empress', nameCN: '皇后', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d2/RWS_Tarot_03_Empress.jpg', upright: '丰饶，母性，自然', reversed: '依赖，贫瘠，嫉妒' },
  { name: 'The Emperor', nameCN: '皇帝', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c3/RWS_Tarot_04_Emperor.jpg', upright: '权威，结构，控制', reversed: '暴政，僵化，软弱' },
  { name: 'The Hierophant', nameCN: '教皇', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/8d/RWS_Tarot_05_Hierophant.jpg', upright: '传统，信仰，群体', reversed: '反叛，盲从，被束缚' },
  { name: 'The Lovers', nameCN: '恋人', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/RWS_Tarot_06_Lovers.jpg', upright: '爱情，选择，和谐', reversed: '不和谐，分离，错误选择' },
  { name: 'The Chariot', nameCN: '战车', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/9b/RWS_Tarot_07_Chariot.jpg', upright: '意志力，胜利，行动', reversed: '失控，失败，停滞' },
  { name: 'Strength', nameCN: '力量', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f5/RWS_Tarot_08_Strength.jpg', upright: '勇气，耐心，控制', reversed: '软弱，自我怀疑，放纵' },
  { name: 'The Hermit', nameCN: '隐士', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4d/RWS_Tarot_09_Hermit.jpg', upright: '内省，孤独，指引', reversed: '孤立，拒绝沟通，迷失' },
  { name: 'Wheel of Fortune', nameCN: '命运之轮', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/3c/RWS_Tarot_10_Wheel_of_Fortune.jpg', upright: '转折点，运气，循环', reversed: '厄运，抵抗改变，倒退' },
  { name: 'Justice', nameCN: '正义', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/RWS_Tarot_11_Justice.jpg', upright: '公正，真理，法律', reversed: '不公，偏见，逃避' },
  { name: 'The Hanged Man', nameCN: '倒吊人', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/2b/RWS_Tarot_12_Hanged_Man.jpg', upright: '牺牲，新视角，等待', reversed: '无谓牺牲，停滞，挣扎' },
  { name: 'Death', nameCN: '死神', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/RWS_Tarot_13_Death.jpg', upright: '结束，重生，改变', reversed: '抗拒改变，停滞，腐败' },
  { name: 'Temperance', nameCN: '节制', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f8/RWS_Tarot_14_Temperance.jpg', upright: '平衡，耐心，协调', reversed: '失衡，过度，冲突' },
  { name: 'The Devil', nameCN: '恶魔', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/55/RWS_Tarot_15_Devil.jpg', upright: '束缚，欲望，物质', reversed: '打破束缚，觉醒，解脱' },
  { name: 'The Tower', nameCN: '高塔', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/53/RWS_Tarot_16_Tower.jpg', upright: '突变，灾难，启示', reversed: '避免灾难，恐惧，重建' },
  { name: 'The Star', nameCN: '星星', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/db/RWS_Tarot_17_Star.jpg', upright: '希望，灵感，宁静', reversed: '绝望，缺乏信心，失望' },
  { name: 'The Moon', nameCN: '月亮', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/7f/RWS_Tarot_18_Moon.jpg', upright: '幻觉，潜意识，不安', reversed: '清晰，揭露，平静' },
  { name: 'The Sun', nameCN: '太阳', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/17/RWS_Tarot_19_Sun.jpg', upright: '快乐，成功，活力', reversed: '悲伤，暂时的失败，乌云' },
  { name: 'Judgement', nameCN: '审判', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/dd/RWS_Tarot_20_Judgement.jpg', upright: '觉醒，重生，召唤', reversed: '怀疑，逃避，悔恨' },
  { name: 'The World', nameCN: '世界', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/ff/RWS_Tarot_21_World.jpg', upright: '完成，圆满，旅行', reversed: '未完成，缺乏，延迟' },
];

// --- Helper Functions ---
function getRandomCards(count: number, lang: Lang): DrawnCard[] {
  const shuffled = [...MAJOR_ARCANA].sort(() => 0.5 - Math.random());
  const selected = shuffled.slice(0, count);
  
  const posMap = {
      ZH: { single: '核心指引', past: '过去', present: '现在', future: '未来' },
      EN: { single: 'CORE GUIDE', past: 'PAST', present: 'PRESENT', future: 'FUTURE' }
  };

  return selected.map((card, index) => ({
    ...card,
    isReversed: Math.random() > 0.5,
    positionKey: count === 1 ? 'single' : ['past', 'present', 'future'][index],
    position: count === 1 
        ? posMap[lang].single 
        : [posMap[lang].past, posMap[lang].present, posMap[lang].future][index]
  }));
}

const saveHistory = (item: HistoryItem) => {
  const existing = JSON.parse(localStorage.getItem('neo_oracle_history') || '[]');
  localStorage.setItem('neo_oracle_history', JSON.stringify([item, ...existing]));
};

const getHistory = (): HistoryItem[] => {
  return JSON.parse(localStorage.getItem('neo_oracle_history') || '[]');
};

const clearHistory = () => {
    localStorage.removeItem('neo_oracle_history');
}

// --- Components ---

// 1. Layout
const Layout = ({ children, onViewChange, currentView, lang, setLang }: { children: React.ReactNode, onViewChange: (v: View) => void, currentView: View, lang: Lang, setLang: (l: Lang) => void }) => {
    const t = TRANSLATIONS[lang];
    return (
  <div className="flex flex-col min-h-screen text-gray-200 font-mono relative z-10">
    {/* Cyber Header */}
    <header className="p-4 border-b border-cyan-900/50 bg-black/90 backdrop-blur-md sticky top-0 z-50 flex justify-between items-center shadow-[0_0_20px_rgba(0,243,255,0.1)]">
      <div 
        className="flex items-center gap-3 cursor-pointer group" 
        onClick={() => onViewChange('HOME')}
      >
        <div className="relative">
            <Zap className="text-cyan-400 group-hover:text-pink-500 transition-colors w-8 h-8 animate-pulse" />
            <div className="absolute inset-0 bg-cyan-400 blur-lg opacity-20 group-hover:opacity-40 transition-opacity"></div>
        </div>
        <div>
            <h1 className="text-2xl font-black tracking-tighter text-white glitch-text" data-text="NEO-ORACLE">
            NEO-ORACLE
            </h1>
            <div className="flex items-center gap-2 text-[10px] text-cyan-600 tracking-[0.3em] uppercase">
               <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></div>
               {t.systemStatus}
            </div>
        </div>
      </div>
      <nav className="flex gap-4 items-center">
        <button 
            onClick={() => setLang(lang === 'ZH' ? 'EN' : 'ZH')}
            className="flex items-center gap-2 text-xs font-bold text-gray-400 hover:text-white border border-gray-800 px-3 py-1 rounded hover:border-gray-500 transition-all"
        >
            <Globe size={14} /> {lang}
        </button>
        {currentView !== 'HOME' && (
          <button 
            onClick={() => onViewChange('HOME')}
            className="flex items-center gap-2 text-cyan-400 hover:text-cyan-200 transition-colors border border-cyan-900 hover:border-cyan-500 px-4 py-2 rounded-sm clip-corner bg-black/50 hover:bg-cyan-900/30 font-bold"
          >
            <ArrowLeft size={16} /> <span className="hidden sm:inline">{t.abort}</span>
          </button>
        )}
      </nav>
    </header>

    {/* Main Content */}
    <main className="flex-grow p-4 sm:p-8 container mx-auto max-w-6xl relative">
      {children}
    </main>

    {/* Footer */}
    <footer className="p-6 border-t border-cyan-900/30 text-center text-xs text-gray-600 mt-auto bg-black/80">
      <div className="flex flex-col items-center gap-2">
         <p className="font-bold text-cyan-900">{t.footer}</p>
         <p className="opacity-50 max-w-lg">{t.disclaimer}</p>
      </div>
    </footer>
  </div>
)};

// 2. Home View
const HomeView = ({ onViewChange, lang }: { onViewChange: (v: View) => void, lang: Lang }) => {
  const t = TRANSLATIONS[lang];
  return (
    <div className="flex flex-col items-center justify-center min-h-[70vh] gap-16 animate-fade-in relative">
      
      {/* Hero Section */}
      <div className="text-center space-y-6 relative z-10 mt-8">
        <div className="inline-flex items-center gap-2 border border-cyan-500/30 px-4 py-1 rounded-full text-xs text-cyan-400 bg-cyan-900/10 mb-2">
           <Wifi size={12} className="animate-pulse" /> AWAITING USER INPUT
        </div>
        <h2 className="text-5xl md:text-7xl font-black text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 via-white to-pink-500 drop-shadow-[0_0_15px_rgba(0,243,255,0.5)]">
          {t.heroTitle}
        </h2>
        <p className="text-cyan-100/60 max-w-xl mx-auto leading-relaxed text-lg font-light">
          <span className="text-cyan-400">&gt;</span> {t.heroSubtitle1} <br/>
          <span className="text-cyan-400">&gt;</span> {t.heroSubtitle2} <br/>
          {t.heroReady}
        </p>
      </div>

      {/* Cards Grid */}
      <div className="grid md:grid-cols-2 gap-8 w-full max-w-4xl px-4">
        {/* Tarot Card */}
        <div 
          onClick={() => onViewChange('TAROT')}
          className="group relative h-72 cursor-pointer"
        >
          <div className="absolute inset-0 bg-cyan-900/10 border border-cyan-500/30 clip-corner-lg group-hover:bg-cyan-900/20 transition-all duration-300 group-hover:border-cyan-400 group-hover:shadow-[0_0_30px_rgba(0,243,255,0.15)]"></div>
          {/* Corner accents */}
          <div className="absolute top-0 left-0 w-12 h-12 border-t-2 border-l-2 border-cyan-500/50 rounded-tl-sm group-hover:border-cyan-400 transition-colors"></div>
          <div className="absolute bottom-0 right-0 w-12 h-12 border-b-2 border-r-2 border-cyan-500/50 rounded-br-sm group-hover:border-cyan-400 transition-colors"></div>
          
          <div className="relative h-full flex flex-col items-center justify-center p-6 text-center z-10">
            <div className="bg-black p-4 rounded-full mb-6 border border-cyan-500/30 group-hover:scale-110 transition-transform duration-300 shadow-[0_0_15px_rgba(0,243,255,0.2)]">
                <Eye className="w-10 h-10 text-cyan-400" />
            </div>
            <h3 className="text-3xl font-bold text-white mb-3 group-hover:text-cyan-300 transition-colors font-sans tracking-wider">{t.tarotTitle}</h3>
            <p className="text-sm text-cyan-100/50 group-hover:text-cyan-100/80 px-8">
              {t.tarotDesc}
            </p>
            <div className="mt-6 px-6 py-2 bg-cyan-900/20 border border-cyan-500/20 text-xs text-cyan-400 font-bold opacity-60 group-hover:opacity-100 transition-opacity tracking-widest clip-hex">
                INITIALIZE_READING()
            </div>
          </div>
        </div>

        {/* Answer Book Card */}
        <div 
          onClick={() => onViewChange('ANSWER_BOOK')}
          className="group relative h-72 cursor-pointer"
        >
          <div className="absolute inset-0 bg-pink-900/10 border border-pink-500/30 clip-corner-lg group-hover:bg-pink-900/20 transition-all duration-300 group-hover:border-pink-400 group-hover:shadow-[0_0_30px_rgba(255,0,255,0.15)]"></div>
           {/* Corner accents */}
           <div className="absolute top-0 right-0 w-12 h-12 border-t-2 border-r-2 border-pink-500/50 rounded-tr-sm group-hover:border-pink-400 transition-colors"></div>
           <div className="absolute bottom-0 left-0 w-12 h-12 border-b-2 border-l-2 border-pink-500/50 rounded-bl-sm group-hover:border-pink-400 transition-colors"></div>

          <div className="relative h-full flex flex-col items-center justify-center p-6 text-center z-10">
            <div className="bg-black p-4 rounded-full mb-6 border border-pink-500/30 group-hover:scale-110 transition-transform duration-300 shadow-[0_0_15px_rgba(255,0,255,0.2)]">
                <BookOpen className="w-10 h-10 text-pink-400" />
            </div>
            <h3 className="text-3xl font-bold text-white mb-3 group-hover:text-pink-300 transition-colors font-sans tracking-wider">{t.answerTitle}</h3>
            <p className="text-sm text-pink-100/50 group-hover:text-pink-100/80 px-8">
              {t.answerDesc}
            </p>
            <div className="mt-6 px-6 py-2 bg-pink-900/20 border border-pink-500/20 text-xs text-pink-400 font-bold opacity-60 group-hover:opacity-100 transition-opacity tracking-widest clip-hex">
                QUERY_MATRIX()
            </div>
          </div>
        </div>
      </div>

      {/* History Button */}
      <div className="mt-8 w-full max-w-md px-4 opacity-80 hover:opacity-100 transition-opacity">
          <HistorySection compact lang={lang} />
      </div>
    </div>
  );
};

// 3. Tarot View
const TarotView = ({ lang }: { lang: Lang }) => {
  const [stage, setStage] = useState<'SETUP' | 'SHUFFLE' | 'SPREAD' | 'READING'>('SETUP');
  const [topic, setTopic] = useState('');
  const [spreadType, setSpreadType] = useState<'SINGLE' | 'TIME'>('TIME');
  const [cards, setCards] = useState<DrawnCard[]>([]);
  const [interpretation, setInterpretation] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  
  const t = TRANSLATIONS[lang];

  const startReading = async () => {
    if (!process.env.API_KEY) {
      setInterpretation(t.errNoKey);
      return;
    }
    setIsLoading(true);
    
    // Construct card description for AI
    const cardsDesc = cards.map((c, i) => 
      `${i + 1}. ${c.name} (${c.nameCN}) [${c.isReversed ? 'Reversed/逆位' : 'Upright/正位'}] - Position: ${c.position}`
    ).join('\n');

    const prompt = `
      Role: Cyberpunk Oracle (Year 2077). 
      Language: ${lang === 'ZH' ? 'Simplified Chinese' : 'English'}.
      
      Tone: Cool, objective, mysterious, digital. Use metaphors related to code, glitches, algorithms, network protocols, and neon-noir aesthetics.
      
      User Query: "${topic || (lang === 'ZH' ? '整体运势' : 'General Fortune')}"
      
      Drawn Cards (Rider-Waite Data):
      ${cardsDesc}
      
      Task:
      1. Briefly decode the data stream of each card in its specific position. Connect the card imagery to cybernetic/hacker concepts.
      2. Provide a final "System Projection" (Summary).
      
      Format: 
      - Use Markdown. 
      - Bold key terms.
      - Keep it concise and impactful.
    `;

    try {
      const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
      });
      
      const text = response.text || t.errSignalLost;
      setInterpretation(text);
      
      saveHistory({
        id: Date.now().toString(),
        type: 'TAROT',
        date: new Date().toLocaleString(),
        query: topic || (lang === 'ZH' ? '整体运势' : 'General Fortune'),
        result: text,
        details: cards
      });

    } catch (e) {
      console.error(e);
      setInterpretation(t.errConnect);
    } finally {
      setIsLoading(false);
    }
  };

  const handleDraw = () => {
    setStage('SHUFFLE');
    // Fake shuffle time
    setTimeout(() => {
      const count = spreadType === 'SINGLE' ? 1 : 3;
      const drawn = getRandomCards(count, lang);
      setCards(drawn);
      setStage('SPREAD');
    }, 2500); 
  };

  useEffect(() => {
    if (stage === 'SPREAD' && cards.length > 0) {
        const timer = setTimeout(() => {
            startReading();
            setStage('READING');
        }, 1500);
        return () => clearTimeout(timer);
    }
  }, [stage, cards]);

  // Setup Stage
  if (stage === 'SETUP') {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] space-y-10 animate-fade-in max-w-2xl mx-auto pt-8">
        <div className="text-center space-y-2">
             <h2 className="text-3xl text-cyan-400 font-bold tracking-tight">{t.tarotSetupTitle}</h2>
             <div className="h-1 w-32 bg-cyan-500/50 mx-auto rounded-full shadow-[0_0_10px_#00f3ff]"></div>
             <p className="text-xs text-gray-500">Protocol v2.4: Secure Connection</p>
        </div>
        
        <div className="w-full space-y-8 bg-gray-900/40 p-8 md:p-12 rounded-sm border-l border-r border-cyan-500/30 relative overflow-hidden clip-corner-lg">
            {/* Deco lines */}
            <div className="absolute top-0 left-0 w-full h-[1px] bg-gradient-to-r from-transparent via-cyan-500 to-transparent opacity-50"></div>
            <div className="absolute bottom-0 left-0 w-full h-[1px] bg-gradient-to-r from-transparent via-cyan-500 to-transparent opacity-50"></div>

          <div className="space-y-3">
            <label className="flex items-center gap-2 text-sm text-cyan-300 font-bold tracking-wider uppercase">
                <Terminal size={16} /> 
                {t.tarotTarget}
            </label>
            <input 
              type="text" 
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              placeholder={t.tarotPlaceholder}
              className="w-full bg-black/80 border border-gray-700 p-4 text-white focus:border-cyan-400 focus:shadow-[0_0_15px_rgba(0,243,255,0.3)] outline-none transition-all rounded-sm text-lg placeholder-gray-600"
            />
          </div>

          <div className="space-y-3">
            <label className="flex items-center gap-2 text-sm text-cyan-300 font-bold tracking-wider uppercase">
                <Cpu size={16} /> 
                {t.tarotAlgo}
            </label>
            <div className="grid grid-cols-2 gap-4">
              <button 
                onClick={() => setSpreadType('SINGLE')}
                className={`p-6 border transition-all relative overflow-hidden group clip-hex ${spreadType === 'SINGLE' ? 'border-cyan-400 bg-cyan-900/20 text-white shadow-[inset_0_0_20px_rgba(0,243,255,0.1)]' : 'border-gray-800 text-gray-500 hover:border-gray-600 bg-black'}`}
              >
                <div className="relative z-10 text-left">
                    <div className="font-bold text-lg">{t.tarotSingle}</div>
                    <div className="text-xs opacity-60 mt-1 font-mono">{t.tarotSingleDesc}</div>
                </div>
                {spreadType === 'SINGLE' && <div className="absolute right-0 top-0 bottom-0 w-1 bg-cyan-400 shadow-[0_0_10px_#00f3ff]"></div>}
              </button>
              <button 
                onClick={() => setSpreadType('TIME')}
                className={`p-6 border transition-all relative overflow-hidden group clip-hex ${spreadType === 'TIME' ? 'border-cyan-400 bg-cyan-900/20 text-white shadow-[inset_0_0_20px_rgba(0,243,255,0.1)]' : 'border-gray-800 text-gray-500 hover:border-gray-600 bg-black'}`}
              >
                <div className="relative z-10 text-left">
                    <div className="font-bold text-lg">{t.tarotTime}</div>
                    <div className="text-xs opacity-60 mt-1 font-mono">{t.tarotTimeDesc}</div>
                </div>
                 {spreadType === 'TIME' && <div className="absolute right-0 top-0 bottom-0 w-1 bg-cyan-400 shadow-[0_0_10px_#00f3ff]"></div>}
              </button>
            </div>
          </div>

          <button 
            onClick={handleDraw}
            className="w-full mt-6 group relative py-5 px-6 bg-cyan-900/10 overflow-hidden border border-cyan-400/50 text-cyan-400 font-bold tracking-[0.2em] uppercase hover:text-black hover:bg-cyan-400 transition-all duration-300 clip-corner hover:shadow-[0_0_30px_rgba(0,243,255,0.4)]"
          >
            <div className="absolute inset-0 w-full h-full bg-gradient-to-r from-transparent via-white/10 to-transparent translate-x-[-100%] group-hover:translate-x-[100%] transition-transform duration-1000"></div>
            <span className="relative z-10 flex items-center justify-center gap-3 text-lg">
                 {t.tarotBtn} <Zap size={20} className="fill-current" />
            </span>
          </button>
        </div>
      </div>
    );
  }

  // Shuffle Stage
  if (stage === 'SHUFFLE') {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] relative">
        <div className="absolute inset-0 pointer-events-none bg-[radial-gradient(circle_at_center,_rgba(255,0,255,0.1),_transparent_70%)]"></div>
        <div className="relative w-40 h-64 md:w-48 md:h-80">
          {[...Array(5)].map((_, i) => (
            <div 
              key={i}
              className="absolute inset-0 border border-pink-500/50 bg-black rounded-lg flex items-center justify-center shadow-[0_0_15px_rgba(255,0,255,0.2)]"
              style={{
                transform: `translate(${i * 2}px, ${i * 2}px)`,
                animation: `shuffle-anim 0.8s infinite alternate ease-in-out`,
                animationDelay: `${i * 0.1}s`
              }}
            >
              {/* Cyber Pattern on back */}
              <div className="w-full h-full opacity-40 bg-[linear-gradient(45deg,#222_25%,transparent_25%,transparent_75%,#222_75%,#222),linear-gradient(45deg,#222_25%,transparent_25%,transparent_75%,#222_75%,#222)] bg-[size:20px_20px] bg-[position:0_0,10px_10px]"></div>
              <div className="absolute inset-4 border border-pink-500/30 flex items-center justify-center rounded">
                  <div className="w-16 h-16 border-t-2 border-b-2 border-pink-500 rounded-full animate-spin-slow"></div>
              </div>
              <Cpu className="text-pink-500 absolute w-8 h-8 animate-pulse" />
            </div>
          ))}
        </div>
        <div className="mt-16 text-center space-y-2 relative z-10 bg-black/50 p-4 rounded border border-pink-900/50 backdrop-blur-sm">
            <h3 className="text-2xl font-bold text-pink-500 glitch-text" data-text={t.tarotShuffling}>{t.tarotShuffling}</h3>
            <p className="text-xs text-pink-300/70 font-mono typing-effect w-fit mx-auto pr-2">{t.tarotAccessing}</p>
        </div>
        <style>{`
          @keyframes shuffle-anim {
            0% { transform: translate(0,0) rotate(0deg); z-index: 1; }
            25% { transform: translate(-30px, -10px) rotate(-5deg); z-index: 5; }
            50% { transform: translate(0,0) rotate(0deg); z-index: 1; }
            75% { transform: translate(30px, 10px) rotate(5deg); z-index: 5; }
            100% { transform: translate(0,0) rotate(0deg); z-index: 1; }
          }
        `}</style>
      </div>
    );
  }

  // Spread & Reading Stage
  return (
    <div className="animate-fade-in pb-20">
      {/* Card Display */}
      <div className="flex flex-wrap justify-center gap-6 md:gap-12 mb-12 perspective-1000 pt-8">
        {cards.map((card, idx) => (
            <TarotCardDisplay key={idx} card={card} delay={idx * 400} revealed={stage === 'READING' || stage === 'SPREAD'} lang={lang} />
        ))}
      </div>

      {/* Reading Result */}
      <div className="max-w-4xl mx-auto relative mt-12">
        
        <div className="bg-black/80 border border-gray-800 p-6 md:p-10 clip-corner-lg shadow-[0_0_50px_rgba(0,0,0,0.8)] backdrop-blur-xl relative overflow-hidden">
             {/* Background Detail */}
             <div className="absolute right-0 top-0 w-32 h-32 bg-cyan-500/5 rounded-full blur-3xl pointer-events-none"></div>

            <div className="flex items-center justify-between border-b border-gray-800 pb-4 mb-6 relative z-10">
                <div>
                    <h3 className="text-2xl font-bold text-white flex items-center gap-3">
                        <ShieldCheck className="text-cyan-400" /> 
                        {t.tarotReportTitle}
                    </h3>
                    <p className="text-xs text-gray-500 font-mono mt-1 uppercase">Target: {topic || 'GENERAL'} | Model: GEMINI-2.5-FLASH</p>
                </div>
                <div className="flex items-center gap-2">
                   <div className="text-[10px] text-gray-600 font-mono hidden md:block">STATUS:</div>
                   <div className={`px-2 py-1 rounded text-[10px] font-bold border ${isLoading ? 'border-yellow-600 text-yellow-500 bg-yellow-900/20' : 'border-green-600 text-green-500 bg-green-900/20'}`}>
                       {isLoading ? t.tarotStatusProcessing : t.tarotStatusComplete}
                   </div>
                </div>
            </div>

            {isLoading ? (
            <div className="space-y-6 font-mono text-sm text-cyan-400/80 py-8">
                <div className="flex flex-col gap-2">
                    <p className="typing-effect w-full md:w-2/3 border-r-transparent animate-none">> {t.tarotDecrypting}</p>
                    <p className="typing-effect w-full md:w-1/2 border-r-transparent animate-none text-pink-400/80" style={{animationDelay: '0.8s'}}>> {t.tarotAnalyzing}</p>
                    <p className="typing-effect w-full md:w-3/4 border-r-transparent animate-none" style={{animationDelay: '1.8s'}}>> {t.tarotConnecting}</p>
                    <p className="typing-effect w-full border-r-transparent animate-none text-white" style={{animationDelay: '2.8s'}}>> {t.tarotGenerating}</p>
                </div>
                <div className="h-1 bg-gray-800 w-full mt-4 overflow-hidden rounded-full relative">
                    <div className="absolute inset-0 bg-gradient-to-r from-transparent via-cyan-500 to-transparent w-1/2 animate-progress"></div>
                </div>
            </div>
            ) : (
            <div className="prose prose-invert prose-cyan max-w-none prose-p:text-gray-300 prose-strong:text-cyan-400 prose-headings:text-pink-500">
                <ReactMarkdown>{interpretation}</ReactMarkdown>
            </div>
            )}
        </div>

        {!isLoading && (
          <div className="flex justify-center mt-12">
            <button 
                onClick={() => { setStage('SETUP'); setCards([]); setInterpretation(''); }}
                className="flex items-center gap-2 px-8 py-3 border border-gray-700 hover:border-cyan-400 text-gray-400 hover:text-cyan-400 transition-all rounded-sm bg-black hover:bg-cyan-900/20 clip-hex"
            >
                <RotateCcw size={18} /> {t.tarotReset}
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

// 3.1 Individual Tarot Card Component
const TarotCardDisplay = ({ card, delay, revealed, lang }: { card: DrawnCard, delay: number, revealed: boolean, lang: Lang }) => {
    const [flipped, setFlipped] = useState(false);
    
    useEffect(() => {
        if (revealed) {
            const timer = setTimeout(() => setFlipped(true), delay);
            return () => clearTimeout(timer);
        }
    }, [revealed, delay]);

    return (
        <div className="flex flex-col items-center space-y-4 group perspective-1000">
             {/* Position Label */}
             <div className={`text-xs font-bold uppercase tracking-widest px-3 py-1 rounded border transition-colors duration-500 ${flipped ? 'text-cyan-400 border-cyan-900/50 bg-cyan-900/10' : 'text-gray-600 border-gray-800'}`}>
                {card.position}
             </div>
             
             <div 
                className={`relative w-40 h-64 md:w-56 md:h-96 transition-transform duration-1000 transform-style-3d cursor-pointer ${flipped ? 'rotate-y-180' : ''}`}
                onClick={() => setFlipped(!flipped)}
             >
                {/* CARD BACK */}
                <div className="absolute inset-0 w-full h-full backface-hidden rounded-xl overflow-hidden border-2 border-gray-700 bg-gray-900 shadow-lg group-hover:shadow-cyan-500/20 group-hover:border-gray-600 transition-all">
                    {/* Cyber Texture */}
                    <div className="w-full h-full bg-[radial-gradient(circle,rgba(0,243,255,0.1)_1px,transparent_1px)] bg-[size:12px_12px] relative flex flex-col items-center justify-center">
                        <div className="absolute inset-0 bg-gradient-to-br from-black/50 via-transparent to-black/50"></div>
                        <div className="w-3/4 h-3/4 border border-cyan-500/20 rounded flex items-center justify-center relative">
                             <div className="absolute top-0 left-0 w-2 h-2 border-t border-l border-cyan-500"></div>
                             <div className="absolute top-0 right-0 w-2 h-2 border-t border-r border-cyan-500"></div>
                             <div className="absolute bottom-0 left-0 w-2 h-2 border-b border-l border-cyan-500"></div>
                             <div className="absolute bottom-0 right-0 w-2 h-2 border-b border-r border-cyan-500"></div>
                             
                             <Lock className="w-8 h-8 text-gray-600 opacity-50" />
                        </div>
                        <div className="mt-4 text-[10px] text-gray-600 font-mono tracking-widest">ENCRYPTED</div>
                    </div>
                </div>

                {/* CARD FRONT */}
                <div className="absolute inset-0 w-full h-full backface-hidden rotate-y-180 rounded-xl overflow-hidden bg-black shadow-[0_0_30px_rgba(0,0,0,0.5)] border-2 transition-colors duration-500"
                     style={{ borderColor: card.isReversed ? '#ff00ff' : '#00f3ff' }}>
                     
                     <div className="relative w-full h-full">
                        {/* Real Image from Wikimedia */}
                        <img 
                            src={card.imageUrl} 
                            alt={card.name}
                            className={`w-full h-full object-cover transition-transform duration-700 ${card.isReversed ? 'rotate-180' : ''}`}
                            loading="lazy"
                        />
                        
                        {/* Holographic Scan Overlay */}
                        <div className="absolute inset-0 bg-gradient-to-b from-transparent via-white/10 to-transparent opacity-0 group-hover:opacity-100 animate-scan pointer-events-none"></div>
                        
                        {/* Bottom Info Panel */}
                        <div className="absolute bottom-0 inset-x-0 bg-black/80 backdrop-blur-sm p-3 border-t border-gray-800">
                            <div className={`font-bold text-sm text-center ${card.isReversed ? 'text-pink-400' : 'text-cyan-400'}`}>
                                {lang === 'ZH' ? card.nameCN : card.name}
                            </div>
                            <div className="flex justify-between items-center mt-1 px-2">
                                <span className="text-[8px] text-gray-500 font-mono">{lang === 'ZH' ? card.name.toUpperCase() : card.nameCN}</span>
                                {card.isReversed && <span className="text-[8px] bg-pink-900 text-pink-200 px-1 rounded">REV</span>}
                            </div>
                        </div>
                     </div>
                </div>
             </div>
        </div>
    )
}

// 4. Answer Book View
const AnswerBookView = ({ lang }: { lang: Lang }) => {
  const [question, setQuestion] = useState('');
  const [answer, setAnswer] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);
  
  const t = TRANSLATIONS[lang];

  useEffect(() => {
      inputRef.current?.focus();
  }, []);

  const getAnswer = async () => {
    if (!question.trim()) return;
    if (!process.env.API_KEY) {
       setAnswer(t.errNoKey);
       return;
    }

    setIsGenerating(true);
    setAnswer('');

    try {
      const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
      const prompt = `User question: "${question}".
      Language: ${lang === 'ZH' ? 'Simplified Chinese' : 'English'}.
      Role: Cyberpunk Answer Book / AI Core.
      Task: Provide a short, punchy, slightly nihilistic or philosophical answer.
      Constraint: Max 15 words.
      Style Examples: "Access Denied", "404: Meaning Not Found", "Execute Immediately", "Trust the Algorithm", "Reboot Your Life".
      Just the answer, no explanation.`;

      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
      });

      const text = response.text?.trim() || t.errSignalLost;
      
      // Artificial delay for "Computing" effect
      setTimeout(() => {
        setAnswer(text);
        saveHistory({
            id: Date.now().toString(),
            type: 'ANSWER',
            date: new Date().toLocaleString(),
            query: question,
            result: text
        });
      }, 1500);

    } catch (e) {
      setAnswer(t.errConnect);
    } finally {
      setTimeout(() => setIsGenerating(false), 1500);
    }
  };

  return (
    <div className="flex flex-col items-center min-h-[70vh] justify-center animate-fade-in px-4 pt-8">
      <div className="w-full max-w-xl bg-black/80 border border-pink-900/50 p-8 md:p-12 relative clip-corner-lg shadow-[0_0_40px_rgba(255,0,255,0.1)] backdrop-blur-md">
        {/* Decorative neon bars */}
        <div className="absolute -top-1 -right-1 w-16 h-16 border-t-2 border-r-2 border-pink-600 rounded-tr-none"></div>
        <div className="absolute -bottom-1 -left-1 w-16 h-16 border-b-2 border-l-2 border-pink-600 rounded-bl-none"></div>

        <div className="text-center mb-12">
             <BookOpen className="w-12 h-12 text-pink-500 mx-auto mb-4 animate-pulse-fast filter drop-shadow-[0_0_8px_#ff00ff]" />
             <h2 className="text-4xl font-black text-white tracking-tighter glitch-text" data-text={t.abTitle}>{t.abTitle}</h2>
             <p className="text-xs text-pink-500/50 mt-2 tracking-widest uppercase">Neural Network Oracle</p>
        </div>

        {!answer ? (
          <div className="space-y-8">
            <div className="relative group">
                <input
                ref={inputRef}
                type="text"
                placeholder={t.abInputPlaceholder}
                value={question}
                onChange={(e) => setQuestion(e.target.value)}
                className="w-full bg-gray-900/50 border-b-2 border-pink-900 focus:border-pink-500 text-center p-4 text-xl text-white outline-none transition-all placeholder-gray-600 font-mono focus:bg-gray-900/80"
                onKeyDown={(e) => e.key === 'Enter' && getAnswer()}
                />
                <div className="absolute bottom-0 left-0 w-full h-[2px]">
                    <div className="h-full bg-pink-500 w-0 transition-all duration-500 ease-out group-focus-within:w-full shadow-[0_0_10px_#ff00ff]"></div>
                </div>
            </div>
            
            <button 
              onClick={getAnswer}
              disabled={isGenerating || !question}
              className={`w-full py-4 neon-button border border-pink-500 text-pink-500 font-bold tracking-widest hover:bg-pink-500 hover:text-black transition-all clip-hex relative overflow-hidden ${isGenerating ? 'opacity-50 cursor-not-allowed' : ''}`}
            >
              <div className="absolute inset-0 bg-white/20 translate-y-full group-hover:translate-y-0 transition-transform"></div>
              {isGenerating ? t.abBtnBusy : t.abBtnIdle}
            </button>
          </div>
        ) : (
          <div className="text-center space-y-10 py-4 animate-fade-in">
            <div className="text-xs text-gray-500 font-mono border-b border-gray-800 pb-2 uppercase tracking-wider">
                {t.abSubject}: {question}
            </div>
            
            <div className="relative py-8">
                {/* Glitch effect container */}
                <div className="text-3xl md:text-5xl font-black text-transparent bg-clip-text bg-gradient-to-br from-white to-pink-500 filter drop-shadow-[0_0_8px_rgba(255,0,255,0.8)] leading-tight">
                {answer}
                </div>
                <div className="absolute -inset-10 bg-pink-500/5 blur-2xl -z-10 rounded-full"></div>
            </div>

            <div className="flex justify-center">
               <button 
                 onClick={() => { setAnswer(''); setQuestion(''); }}
                 className="text-xs text-gray-400 hover:text-pink-400 flex items-center gap-2 border border-gray-800 px-6 py-3 hover:border-pink-500 transition-all uppercase tracking-widest"
               >
                 <RotateCcw size={14} /> {t.abNewQuery}
               </button>
            </div>
          </div>
        )}
      </div>
      
      {/* History specific to Answers */}
      <div className="mt-16 w-full max-w-xl">
         <div className="flex items-center gap-4 mb-4">
            <div className="h-[1px] flex-grow bg-gray-800"></div>
            <h3 className="text-[10px] text-gray-500 font-bold uppercase tracking-[0.2em]">{t.histRecent}</h3>
            <div className="h-[1px] flex-grow bg-gray-800"></div>
         </div>
         <HistorySection typeFilter="ANSWER" compact lang={lang} />
      </div>
    </div>
  );
};

// 5. History Component
const HistorySection = ({ typeFilter, compact, lang }: { typeFilter?: 'TAROT' | 'ANSWER', compact?: boolean, lang: Lang }) => {
  const [history, setHistory] = useState<HistoryItem[]>([]);
  const t = TRANSLATIONS[lang];

  useEffect(() => {
    const load = () => {
      let h = getHistory();
      if (typeFilter) h = h.filter(i => i.type === typeFilter);
      setHistory(h);
    };
    load();
    const interval = setInterval(load, 2000);
    return () => clearInterval(interval);
  }, [typeFilter]);

  if (history.length === 0) return null;

  const displayItems = compact ? history.slice(0, 3) : history;

  return (
    <div className="w-full animate-fade-in">
      {!compact && (
         <div className="flex justify-between items-center mb-6 bg-black/50 p-4 border border-gray-800">
            <h2 className="text-xl font-bold text-cyan-400 flex items-center gap-2">
                <History /> {t.histTitle}
            </h2>
            <button onClick={() => { clearHistory(); setHistory([]); }} className="text-xs text-red-400 hover:text-red-300 border border-red-900/50 hover:border-red-500 px-3 py-1 transition-colors">
                {t.histPurge}
            </button>
         </div>
      )}
      
      <div className="space-y-3">
        {displayItems.map(item => (
          <div key={item.id} className="group bg-black/40 border-l-2 border-gray-800 hover:border-cyan-500 p-4 transition-all hover:bg-gray-900/60 relative overflow-hidden">
             <div className="absolute inset-0 bg-cyan-400/5 translate-x-[-100%] group-hover:translate-x-0 transition-transform duration-500"></div>
            <div className="flex justify-between text-[10px] text-gray-500 mb-2 font-mono uppercase tracking-wider relative z-10">
               <span className={item.type === 'TAROT' ? 'text-cyan-600' : 'text-pink-600'}>[{item.type}]</span>
               <span>{item.date}</span>
            </div>
            <div className="font-bold text-gray-300 text-sm mb-1 relative z-10">{item.query}</div>
            <div className="text-xs text-gray-500 font-mono truncate opacity-70 group-hover:opacity-100 transition-opacity relative z-10">
               >> {item.result.slice(0, 60)}...
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};


// --- Main App Component ---
const App = () => {
  const [currentView, setCurrentView] = useState<View>('HOME');
  const [lang, setLang] = useState<Lang>('ZH');

  const renderView = () => {
    switch (currentView) {
      case 'HOME': return <HomeView onViewChange={setCurrentView} lang={lang} />;
      case 'TAROT': return <TarotView lang={lang} />;
      case 'ANSWER_BOOK': return <AnswerBookView lang={lang} />;
      default: return <HomeView onViewChange={setCurrentView} lang={lang} />;
    }
  };

  return (
    <Layout onViewChange={setCurrentView} currentView={currentView} lang={lang} setLang={setLang}>
      {renderView()}
    </Layout>
  );
};

const root = createRoot(document.getElementById('root')!);
root.render(<App />);
